version: '3.8'

services:
  app:
    build:
      context: .
    container_name: employee_api
    volumes:
      - ./app:/app
    ports:
      - "3000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=postgrespassword;Database=mydb;

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
